services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: anime-api
        container_name: anime-api
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: postgres:17-alpine
        container_name: main-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laraveluser
            POSTGRES_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
